$store = [System.IO.File]::ReadAllText("$PSScriptRoot\..\js\store.js", [System.Text.Encoding]::UTF8)
$tt = [System.IO.File]::ReadAllText("$PSScriptRoot\..\js\timetable.js", [System.Text.Encoding]::UTF8)
$stats = [System.IO.File]::ReadAllText("$PSScriptRoot\..\js\statistics.js", [System.Text.Encoding]::UTF8)
$matrix = [System.IO.File]::ReadAllText("$PSScriptRoot\..\js\matrix.js", [System.Text.Encoding]::UTF8)
$retro = [System.IO.File]::ReadAllText("$PSScriptRoot\..\js\retroLogView.js", [System.Text.Encoding]::UTF8)
$runner = [System.IO.File]::ReadAllText("$PSScriptRoot\m1_challenger2_browser_runner.js", [System.Text.Encoding]::UTF8)
$css = [System.IO.File]::ReadAllText("$PSScriptRoot\..\css\styles.css", [System.Text.Encoding]::UTF8)

$sb = [System.Text.StringBuilder]::new()
$null = $sb.AppendLine('<!DOCTYPE html>')
$null = $sb.AppendLine('<html lang="zh-TW" data-theme="kitty">')
$null = $sb.AppendLine('<head>')
$null = $sb.AppendLine('  <meta charset="UTF-8">')
$null = $sb.AppendLine('  <title>ClassQuant Hub - M1 Challenger 2 Browser Empirical Runner</title>')
$null = $sb.AppendLine('  <style>')
$null = $sb.AppendLine($css)
$null = $sb.AppendLine('    body { font-family: sans-serif; padding: 20px; margin: 0; background: #fff5f7; }')
$null = $sb.AppendLine('    .pass { color: #16a34a; font-weight: bold; }')
$null = $sb.AppendLine('    .fail { color: #dc2626; font-weight: bold; }')
$null = $sb.AppendLine('    .hidden { display: none !important; }')
$null = $sb.AppendLine('    #test-workspace { margin-top: 20px; padding: 15px; background: white; border-radius: 16px; border: 1px solid #fbcfe8; }')
$null = $sb.AppendLine('  </style>')
$null = $sb.AppendLine('</head>')
$null = $sb.AppendLine('<body>')
$null = $sb.AppendLine('  <h1>ClassQuant Hub - M1 Challenger 2 Empirical Test Suite</h1>')
$null = $sb.AppendLine('  <div id="status">Initializing empirical verification tests...</div>')
$null = $sb.AppendLine('  <pre id="summary-json" style="background: #1e293b; color: #f8fafc; padding: 15px; border-radius: 8px; font-family: monospace; font-size: 12px; max-height: 400px; overflow-y: auto;"></pre>')
$null = $sb.AppendLine('  <script id="summary-data" type="application/json"></script>')
$null = $sb.AppendLine('  <div id="test-workspace">')
$null = $sb.AppendLine('    <div id="classroom-matrix-view"></div>')
$null = $sb.AppendLine('    <div id="retro-log-view"></div>')
$null = $sb.AppendLine('    <div id="global-modal" class="hidden"><div id="global-modal-content"></div></div>')
$null = $sb.AppendLine('  </div>')
$null = $sb.AppendLine('  <script>')
$null = $sb.AppendLine('    window.lucide = { createIcons: () => {} };')
$null = $sb.AppendLine('  </script>')
$null = $sb.AppendLine('  <script>')
$null = $sb.AppendLine('// --- store.js ---')
$null = $sb.AppendLine($store)
$null = $sb.AppendLine('// --- timetable.js ---')
$null = $sb.AppendLine($tt)
$null = $sb.AppendLine('// --- statistics.js ---')
$null = $sb.AppendLine($stats)
$null = $sb.AppendLine('// --- matrix.js ---')
$null = $sb.AppendLine($matrix)
$null = $sb.AppendLine('// --- retroLogView.js ---')
$null = $sb.AppendLine($retro)
$null = $sb.AppendLine('// --- test runner ---')
$null = $sb.AppendLine($runner)
$null = $sb.AppendLine('  </script>')
$null = $sb.AppendLine('</body>')
$null = $sb.AppendLine('</html>')

$outPath = Join-Path $PSScriptRoot "m1_challenger2_browser_runner.html"
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "Bundled $outPath successfully! Total bytes: $([System.IO.FileInfo]::new($outPath).Length)"
